## El método de K means

In [1]:
import numpy as np

In [3]:
## creamos un array de números aleatorios y luego lo convertimos en un array de 3 dimensiones
data=np.random.random(90).reshape(30,3)
data

array([[0.82180789, 0.30955308, 0.04362941],
       [0.93063116, 0.42128077, 0.54534706],
       [0.11630002, 0.51152244, 0.51143022],
       [0.23437735, 0.95088927, 0.68198594],
       [0.39700304, 0.40431593, 0.13619412],
       [0.143205  , 0.2024942 , 0.22923261],
       [0.89230924, 0.45101785, 0.64959483],
       [0.6919923 , 0.63682781, 0.95018196],
       [0.16959677, 0.64920334, 0.74522038],
       [0.55197473, 0.459771  , 0.71457404],
       [0.5312281 , 0.35852254, 0.64201597],
       [0.80146684, 0.38042167, 0.78286955],
       [0.43811688, 0.22771617, 0.07379854],
       [0.8081853 , 0.59916269, 0.67710168],
       [0.73120577, 0.95760248, 0.61019304],
       [0.98800025, 0.59536194, 0.63780146],
       [0.22504563, 0.11587709, 0.92480044],
       [0.11831646, 0.89114162, 0.75969626],
       [0.19955425, 0.57647882, 0.12772184],
       [0.32707015, 0.92128237, 0.07027793],
       [0.61870364, 0.05915115, 0.26116553],
       [0.10276085, 0.91711293, 0.07706664],
       [0.

In [12]:
## recordemos que el método k means necesita dos centroides
## seleccionamos de los datos dos centroides al azar
centro1=np.random.choice(len(data))
centro2=np.random.choice(len(data))
## colocamos un centroide debajo del otro
clust_center=np.vstack([data[centro1], data[centro2]])
clust_center

array([[0.98800025, 0.59536194, 0.63780146],
       [0.32707015, 0.92128237, 0.07027793]])

In [13]:
from scipy.cluster.vq import vq

In [15]:
print("Devuelve en primer instancia a que cluster pertenece cada información")
print("La segunda parte nos devuelve la distancia que tiene cada punto con el baricentro")
vq(data, clust_center)

Devuelve en primer instancia a que cluster pertenece cada información


(array([0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1,
        1, 1, 1, 1, 0, 1, 1, 1]),
 array([0.67996105, 0.20528829, 0.63792053, 0.61939908, 0.52582303,
        0.75876836, 0.17358302, 0.43234442, 0.74456174, 0.46303043,
        0.51454004, 0.31943509, 0.70240861, 0.1840988 , 0.44488633,
        0.        , 0.94571342, 0.72096061, 0.37208816, 0.        ,
        0.75216794, 0.22445073, 0.29346497, 0.75742913, 0.41682852,
        0.55610082, 0.46506422, 0.31280909, 0.19459894, 0.81593178]))

In [17]:
from scipy.cluster.vq import kmeans

In [18]:
#implementar el método kmeans directamente
## el resultado el la súma de los cuadrados de los errores
## el útimo dato es el normalizado, la distancia de cada punto y las eleva al cuadrado
## súma la distancia de cada punto y las eleva al cuadrado
kmeans(data, clust_center)

(array([[0.70375629, 0.46865067, 0.62757829],
        [0.20173229, 0.64639945, 0.35760456]]),
 0.35416380632606687)