# NUMPY

## Arreglos

In [1]:
## Importar numpy
import numpy as np

In [2]:
## crear un arreglo de numeros enteros
array=np.array([1,2,4,5])
array

array([1, 2, 4, 5])

In [3]:
## saber el tipo de dato del array
type(array)

numpy.ndarray

In [4]:
## saber el tamaño del arreglo
array.size

4

In [5]:
## saber el numero de dimensiones
array.ndim

1

In [6]:
## conocer el tipo de dato contenido en el array
array.dtype

dtype('int32')

In [7]:
## conocer la cantidad de elementos por dimension
array.shape

(4,)

In [8]:
## practica
## crear un arreglo
nombres_personas=np.array(["gerson", "juan", "fernando"])

In [9]:
## saber los tipos de datos contenidos
nombres_personas.dtype

dtype('<U8')

In [10]:
## saber las dimensiones del array
nombres_personas.ndim

1

In [11]:
## saber la cantidad de elementos por dimension
nombres_personas.shape

(3,)

In [12]:
## practicas rapidas
cosas=np.array([[1,2,3,4],  [1,1,1,1], ["a", "a", "b", "c"]])

In [13]:
cosas.ndim

2

In [14]:
cosas.dtype

dtype('<U11')

In [15]:
cosas.shape

(3, 4)

## Operaciones

In [16]:
## crear un arreglo de 5 numeros aletorios, entre el 0 y 10 
array=np.random.randint(0,10, 5, int)
array

array([3, 1, 9, 8, 6])

In [17]:
## sumar 5 a cada elemento del array
array_con_suma=array+5
array_con_suma

array([ 8,  6, 14, 13, 11])

In [18]:
## multiplicar por dos cada elemento del array
array_multiplicado=array*2
array_multiplicado

array([ 6,  2, 18, 16, 12])

In [19]:
## dividir entre tres cada elemento del array
array_dividido=array/3
array_dividido

array([1.        , 0.33333333, 3.        , 2.66666667, 2.        ])

In [20]:
## multiplicar contenido de un array por 10
array_multiplicacion=array*5
array_multiplicacion

array([15,  5, 45, 40, 30])

## Tipos de datos

In [21]:
## para cambiar el tipo de dato que almacena cada array se puede utilizar la palabra reservada dtype
## sintaxis: nombre_variable=numy.array([elementos], dtype=numpy.tipo_de_dato)
## ejemplos

In [22]:
## array que almacené enteros
array_de_enteros=np.array([1,2,4,5,67], dtype=np.int)
array_de_enteros

array([ 1,  2,  4,  5, 67])

In [23]:
## array de elementos booleanos, solo los 0 son convertidos en falso
array_de_booleanos=np.array([0,1,0,1], dtype=np.bool)
array_de_booleanos

array([False,  True, False,  True])

In [24]:
## array de números complejos
array_de_complejos=np.array([2,3,2,3,4], dtype=np.complex)
array_de_complejos

array([2.+0.j, 3.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [25]:
## array de strings
array_de_strings=np.array([4,3,2,3], dtype=np.str)
array_de_strings

array(['4', '3', '2', '3'], dtype='<U1')

In [26]:
## array de numeros flotantes
array_de_flotantes=np.array([2,3,3,3], dtype=np.float)
array_de_flotantes

array([2., 3., 3., 3.])

In [27]:
## array random con tipo de dato entero
array_random_entero=np.array(np.random.rand(20)*20, dtype=np.int)
array_random_entero

array([ 3, 12, 15, 12, 12,  3,  7,  2,  2, 11,  1,  1, 16, 19, 18, 11,  8,
       10, 14, 10])

In [28]:
## array de números aleatorios usando numpy
array_random_numpy=np.random.randint(0,100, 20, int)
array_random_numpy

array([96, 78, 56, 49, 73, 76, 35, 88, 51, 43, 63, 54, 77, 74, 13,  2, 28,
       78, 91,  0])

In [29]:
## crear numeros aleatorios de acuerdo a un rango 
## sintaxis: numpy.arange(rango_inicio, rango_final, incremento, dtype=tipo_de_dato)
## ejemplo:
np.arange(0,100, 5, dtype=np.float)

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50., 55., 60.,
       65., 70., 75., 80., 85., 90., 95.])

In [30]:
## otros ejemplos

In [31]:
np.arange(40, 10, -2)

array([40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16, 14, 12])

In [32]:
np.arange(100, 10)

array([], dtype=int32)

In [33]:
np.arange(100, 120, 4, dtype=np.complex)

array([100.+0.j, 104.+0.j, 108.+0.j, 112.+0.j, 116.+0.j])

In [34]:
np.arange(20,20, 2)

array([], dtype=int32)

In [35]:
## crear array con ceros
## sintaxis: numpy.zeros(numero_de_ceros, dtype=tipo_de_dato)
## ejemplo:
np.zeros(30)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
## Otros ejemplos

In [37]:
np.zeros(20, dtype=np.int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
## relenar un array con unos
## sintaxis: numpy.ones(numero_de_elementos, dtype=numpy.tipo_de_dato)
## ejemplo:
np.ones(30)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [39]:
## otros ejemplos

In [40]:
np.ones(40, dtype=np.int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [41]:
np.ones(-20, dtype=np.str)

ValueError: negative dimensions are not allowed

In [ ]:
## crear un array con numeros cualesquiera
## sintaxis numpy.empty(cantidad_de_elementos, dtype=np.tipo_de_dato)
## ejemplo:
np.empty(20)

array([1.69109959e-306, 1.86921415e-306, 4.45057637e-308, 1.42419530e-306,
       7.56603881e-307, 9.34598925e-307, 1.60220393e-306, 1.11255866e-306,
       8.90098127e-307, 7.56603881e-307, 7.56599807e-307, 9.34607074e-307,
       1.11260416e-306, 8.90051274e-307, 9.34598925e-307, 1.37961913e-306,
       1.37961438e-306, 4.45057637e-308, 1.20160711e-306, 3.75602390e-317])

In [ ]:
np.empty(10, dtype=np.int)

array([1061798576,        713,          0,    5570652,        704,
                0,        768,        713,    6357094,          0])

In [ ]:
## crear un arreglo de números enteros aleatorios
## sintaxis: numpy.random.randint(inicio_del_rango, final_del_rango, numero_de_elementos, tipo)
## ejemplo:
np.random.randint(0, 100, 10)

array([95, 44, 55, 96, 41, 33, 42, 24, 88,  3])

In [ ]:
np.random.randint(10,20,5)

array([12, 16, 11, 10, 12])

## Obtener y actualizar elementos

In [ ]:
## creamos un array para usar
array=np.random.randint(0,10, 10)
array

array([9, 4, 6, 9, 9, 4, 2, 9, 0, 1])

In [ ]:
## obtener el elemento de la posicion 5
array[5]

4

In [ ]:
## cambiar el elemento de la posicion 5
array[5]=100
array

array([  9,   4,   6,   9,   9, 100,   2,   9,   0,   1])

## SubArreglos

In [ ]:
## arreglo para las pruebas
array=np.arange(0,20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
## obtener el sub array de la posicion 1 a la 8
sub_array_1_8=array[1:8]
sub_array_1_8

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
## obtener sub array salteado
sub_array_salteado=array[::2]
sub_array_salteado

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
##obtener el sub array que empiece en la posicion 5
array_inicio_5=array[5:]
array_inicio_5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
## array que termine en la poscion 8
array_final_posicion_8=array[:8]
array_final_posicion_8

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
## array con posiciones especificadas
array_posiciones_especificadas=array[[2,4,6]]
array_posiciones_especificadas

array([2, 4, 6])

In [ ]:
## array con booleanos
array_con_booleanos=array[[True, False, True, False, True]]
array_con_booleanos

IndexError: boolean index did not match indexed array along dimension 0; dimension is 20 but corresponding boolean dimension is 5

In [ ]:
## practicas

In [ ]:
## crear un array de números basura y dividir en dos
array_basura=np.empty(20)
array_basura[:int(array_basura.size/2)]
array_basura[int(array_basura.size/2):]


array([7.56599807e-307, 9.34607074e-307, 1.11260416e-306, 8.90051274e-307,
       9.34598925e-307, 1.37961913e-306, 1.37961438e-306, 4.45057637e-308,
       1.20160711e-306, 3.75602390e-317])

## Vectorizar funciones

In [ ]:
## usar funciones con los datos de un array y obtener un resultado por cada elemento del array pasado por la funcion
## tambien podemos usar lambda
## sintaxis: almacenamiento_funcion=numpy.vectoruze(funcion)
## alamacenamiento_funcion(array_entrada)
## Ejemplo:
## creamos una funcion:
def es_par(valor):
    return valor%2==0
## crear un almacenamiento para la función
saber_pares=np.vectorize(es_par)


In [ ]:
## creamos un array, entre el 50 y 80
array_comprobar=np.arange(50,80)
array_comprobar


array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [ ]:
## array cuales son pares
array_pares=saber_pares(array_comprobar)
array_pares

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False])

In [ ]:
## lo mismo pero con lambda
lambda_es_par=lambda valor:valor%2==0
saber_pares=np.vectorize(lambda_es_par)

In [ ]:
## crear array aleatorio de 20 elementos
array_de_20=np.random.randint(0,100, 20)
array_de_20


array([49, 86, 61,  0, 71, 19, 44, 59, 16,  9, 61, 83,  8,  9,  6, 43, 33,
       59, 19, 53])

In [ ]:
## array con true o falso si es par
saber_pares(array_de_20)

array([False,  True, False,  True, False, False,  True, False,  True,
       False, False, False,  True, False,  True, False, False, False,
       False, False])

## Copias y vistas

Copia, es un arreglo echo a base de otro, pero este no guarda ninguna referencia al arreglo original manteniendose independiente

Vista, es arreglo que apunta a un arreglo original

In [ ]:
## crear un elemento base
## array echo apartir de un rango del 10 al 20 con saltos de 3
array_base=np.arange(10, 20, 3)
array_base

array([10, 13, 16, 19])

In [ ]:
## creamos una copia del array
array_copia=array_base.copy()
array_copia

array([10, 13, 16, 19])

In [ ]:
## verificamos que no sean iguales
array_copia is array_base

False

In [ ]:
## verificamos los ids de cada uno de los arreglos
print(id(array_base))
print(id(array_copia))

2140694782960
2140695156416


In [ ]:
## modificamos un array para ver que no tiene referencia al arreglo base
cambiar = lambda valor: "anterior: %s nuevo: %s"%(valor, np.random.rand())
arreglo_aplicar_funcion=np.vectorize(cambiar)
arreglo_aplicar_funcion(array_base)

array(['anterior: 10 nuevo: 0.13729097284575598',
       'anterior: 13 nuevo: 0.010407522041153916',
       'anterior: 16 nuevo: 0.5501647375715655',
       'anterior: 19 nuevo: 0.4315990473060467'], dtype='<U40')

In [ ]:
## revisamos el contenido de la copia
array_copia

array([10, 13, 16, 19])

In [ ]:
## revisamos que las bases sean diferentes
array_base is array_copia.base

False

In [ ]:
## crear dos vistas apartir de un array
array_vista_a=array_base.view()
array_vista_b=array_base.view()

In [ ]:
## visualizamos las vistas y el array base creado
print("vistas sin modidicar")
print(array_vista_a)
print(array_vista_b)
## modificamos la base para ver los cambios en las vistas
## modificamos el primer elemento del array base
array_base[0]=100
print("arry base: ", end="")
print(array_base)
print("arry vista a: ", end="")
print(array_vista_a)
print("arry vista b: ", end="")
print(array_vista_b)

vistas sin modidicar
[100  13  16  19]
[100  13  16  19]
arry base: [100  13  16  19]
arry vista a: [100  13  16  19]
arry vista b: [100  13  16  19]


In [ ]:
## otro cambio
array_base[1]=1000
## ver cambios
print(array_vista_b)
print(array_vista_a)

[ 100 1000   16   19]
[ 100 1000   16   19]


In [ ]:
## ver si la base es la misma
array_base is array_vista_a.base

True

In [ ]:
## verificamos ids
print(id(array_base))
print(id(array_vista_a))
print(id(array_vista_a.base))

2140694831232
2140694915632
2140694831232


## Matrices

In [ ]:
## crear una matriz 3, 5
matriz=np.array([
    np.ones(5),
    np.full(5,2),
    np.full(5,3)
], dtype=np.int)
matriz

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3]])

In [ ]:
## saber el tamaño de la matriz
matriz.ndim

2

In [ ]:
## saber los indices de la matriz
matriz.shape

(3, 5)

In [ ]:
matriz=matriz*np.random.rand()
matriz

array([[0.02552143, 0.02552143, 0.02552143, 0.02552143, 0.02552143],
       [0.05104286, 0.05104286, 0.05104286, 0.05104286, 0.05104286],
       [0.0765643 , 0.0765643 , 0.0765643 , 0.0765643 , 0.0765643 ]])

In [ ]:
## obtener la columna 3
columna_3=matriz[:,2]
columna_3

array([0.02552143, 0.05104286, 0.0765643 ])

In [ ]:
## obtener dos filas de la columna 3
matriz[:2, 2]

array([0.02552143, 0.05104286])

In [ ]:
# obtener los datos de la fila 2
matriz[2,:]

array([0.0765643, 0.0765643, 0.0765643, 0.0765643, 0.0765643])

In [ ]:
#obtener los datos de la fila 3 los ultimos dos datos
matriz[2, :2]

array([0.0765643, 0.0765643])

## Metodos de agreción

In [ ]:
## creamos una matriz
matriz=np.array([
    np.arange(1,6),
    np.arange(1,6),
    np.arange(1,6)
])
matriz[1,:]=matriz[1, :]*10
matriz[2, :]=matriz[2, :]*100
matriz

array([[  1,   2,   3,   4,   5],
       [ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [ ]:
## para saber la desviacion estandar de una matriz
desviacion_estandar=matriz.std()
desviacion_estandar

157.21323099535866

In [ ]:
## para sumar todos los valores
suma=matriz.sum()
suma

1665

In [ ]:
## el número menor
numero_menor=matriz.min()
numero_menor

1

In [ ]:
## numero más grande
numero_mayor=matriz.max()
numero_mayor

500

In [ ]:
## obtener el promedio de los datos
promedio=matriz.mean()
promedio

111.0

In [ ]:
## promedio de la primera fila
matriz[0,:].mean()

3.0

In [ ]:
## sumar la ultima columna
matriz[:, -1].sum()

555

In [ ]:
## sumar la posicion 1 1, 1 2, 2,1, 2,2
matriz[:2, :2].sum()


33

## Transposición

se refiere al intercambio de filas por columnas creando un matriz transpuesta

In [ ]:
## crear una matris random
matriz_random=np.random.randint(0, 10, size=(4,3,2))
matriz_random

array([[[3, 4],
        [8, 1],
        [9, 9]],

       [[1, 5],
        [6, 2],
        [9, 1]],

       [[4, 4],
        [8, 8],
        [3, 0]],

       [[8, 7],
        [9, 3],
        [6, 2]]])

In [ ]:
## saber el tamaño de los ejes
matriz_random.shape

(4, 3, 2)

In [ ]:
## saber el número de dimensiones
matriz.ndim

2

## Filtros y condiciones

In [ ]:
## crear una matriz random
matriz_random=np.random.rand(20)*10
matriz_random

array([1.72006509, 8.99161461, 8.32076096, 9.67919029, 9.75150759,
       1.78121779, 8.40100542, 7.02827138, 5.490507  , 3.92897241,
       1.17843961, 4.53597741, 0.18898512, 9.61862751, 8.66190765,
       8.81365372, 1.28644787, 4.57758613, 0.68721563, 7.57838728])

In [ ]:
## se pueden obtener datos con true y con falso solo devolvera una matriz en donde en esa posicion exista
## el valor true
## sintaxis: matriz[(condiciones)]
matriz_random[(matriz_random>1)]

array([8.89563085, 7.10307245, 9.57318283])

In [ ]:
## ejemplos de true y false
matriz_random[[True, False, True]]

array([8.89563085, 9.57318283])

In [ ]:
## obtener las calificacione por encima del promedio
promedio_calificaciones=matriz_random.mean()
promedio_calificaciones
calificaciones_mayores_al_promedio=matriz_random[(matriz_random>promedio_calificaciones)]
calificaciones_mayores_al_promedio

array([8.99161461, 8.32076096, 9.67919029, 9.75150759, 8.40100542,
       7.02827138, 9.61862751, 8.66190765, 8.81365372, 7.57838728])

In [ ]:
## número de alumnos mayores al promedio
alumnos_mayores_al_promedio=calificaciones_mayores_al_promedio.size
alumnos_mayores_al_promedio

10

In [ ]:
## saber la calificación más alta
calificacion_mas_alta=matriz_random.max()
calificacion_mas_alta

9.7515075871197

In [ ]:
## calificacion minima
calificacion_mas_baja=matriz_random.min()
calificacion_mas_baja

0.18898512473969453

In [ ]:
## saber la desviación estandar
desviacion_estandar=matriz_random.std()
desviacion_estandar

3.3809765053856404

## Condiciones

In [ ]:
## saber si todos los elementos dentro del array cumplen con una condición
## todos los elementos dentro del array deben dar True a la condición pasada
## sintaxis: numpy.all((condicion operador_logico otra_condicion))
## ejemplo:
##creamos un array de ejemplo
array=np.arange(1,20)
print(array)
## saber si todos los numeros son mayores a 0
np.all(array>0)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


True

In [ ]:
## todos los numeros son pares
np.all(array%2==0)


False

In [ ]:
## numpy.any saber si existen elementos que cumplan la condición
## si ningún elemento cumple con la condición retorna falso
## saber si existe algun elemento que sea 1
np.any(array==1)

True

In [ ]:
## saber si existe algún elemento el doble de grande que el promedio
np.any(array>array.mean()*2)

False

In [ ]:
## saber si todos los numeros son mayores a 0
np.all(array>0)

True

In [ ]:
## saber si existe un número mayor al promedio pero menor a 6
np.any((array>array.mean()) & (array<5))

False

## Funciones where y select

Son instrucciones en base a condiciones podemos crear un array del mismo tamaño pero aplicando un nuevo tipo de datoa a la información de acuerdo a ala condición

In [ ]:
## where, esta se utiliza para hacer una condición y rellenar en el nuevo array esa posición
## de acuerdo a si es falso o true
## sintaxis: array.where(condicion, condicion_si, condicion_si_no)
## ejemplo:
## crear un array de iqs
iqs=np.random.randint(60, 300, 30)
iqs

array([263, 106, 214, 218, 130, 104, 288, 297, 109, 172, 201, 234, 104,
       259, 276, 281, 233, 119,  86, 223, 206, 223, 156, 237, 233, 265,
       240,  90, 237, 142])

In [ ]:
## si su iq es mayor a 100 poner es listo, si es menor, poner no tan listo
np.where(iqs>150, "listo", "no tan listo")

array(['listo', 'no tan listo', 'listo', 'listo', 'no tan listo',
       'no tan listo', 'listo', 'listo', 'no tan listo', 'listo', 'listo',
       'listo', 'no tan listo', 'listo', 'listo', 'listo', 'listo',
       'no tan listo', 'no tan listo', 'listo', 'listo', 'listo', 'listo',
       'listo', 'listo', 'listo', 'listo', 'no tan listo', 'listo',
       'no tan listo'], dtype='<U12')

In [ ]:
## poner por debajo del promedio si es menor o igual al promedio, por encima del promdio si es mayor al promedio
np.where(iqs>iqs.mean(), "por encima del promedio", "menor o igual al promedio")

array(['por encima del promedio', 'menor o igual al promedio',
       'por encima del promedio', 'por encima del promedio',
       'menor o igual al promedio', 'menor o igual al promedio',
       'por encima del promedio', 'por encima del promedio',
       'menor o igual al promedio', 'menor o igual al promedio',
       'por encima del promedio', 'por encima del promedio',
       'menor o igual al promedio', 'por encima del promedio',
       'por encima del promedio', 'por encima del promedio',
       'por encima del promedio', 'menor o igual al promedio',
       'menor o igual al promedio', 'por encima del promedio',
       'por encima del promedio', 'por encima del promedio',
       'menor o igual al promedio', 'por encima del promedio',
       'por encima del promedio', 'por encima del promedio',
       'por encima del promedio', 'menor o igual al promedio',
       'por encima del promedio', 'menor o igual al promedio'],
      dtype='<U25')

In [ ]:
## todos los iqs por encima del promedio
iqs[iqs>iqs.mean()]

array([263, 214, 218, 288, 297, 201, 234, 259, 276, 281, 233, 223, 206,
       223, 237, 233, 265, 240, 237])

In [ ]:
## con where
iqs[np.where(iqs>iqs.mean(), True, False)]

array([263, 214, 218, 288, 297, 201, 234, 259, 276, 281, 233, 223, 206,
       223, 237, 233, 265, 240, 237])

In [ ]:
## select es para multiples opciones, diferentes respuestas para diferentes condiciones
condiciones=[iqs>140, iqs>120, iqs>80, iqs>70, iqs<70]
mensaje=["genio", "inteligente", "normal", "tonto", "muy tonto"]
print(iqs)
np.select(condiciones, mensaje)

[263 106 214 218 130 104 288 297 109 172 201 234 104 259 276 281 233 119
  86 223 206 223 156 237 233 265 240  90 237 142]


array(['genio', 'normal', 'genio', 'genio', 'inteligente', 'normal',
       'genio', 'genio', 'normal', 'genio', 'genio', 'genio', 'normal',
       'genio', 'genio', 'genio', 'genio', 'normal', 'normal', 'genio',
       'genio', 'genio', 'genio', 'genio', 'genio', 'genio', 'genio',
       'normal', 'genio', 'genio'], dtype='<U11')

## Guardar archivos

In [ ]:
## guardar un arreglo en un archivo txt
#creamos un arreglo
array_a_guardar=np.random.randint(1,100,10)
##guardar en un archivo
##sintaxis: numpy.savetxt(nombre_archivo, array_a_guardar, smt="tipo_de_dato")
np.savetxt("datos.txt", array_a_guardar, fmt="%f")

In [ ]:
## cargar archivo
datos_cargados=np.loadtxt("datos.txt")

In [ ]:
# %load datos.txt
14.000000
4.000000
84.000000
17.000000
56.000000
98.000000
91.000000
15.000000
87.000000
87.000000


7.0

In [ ]:
datos_cargados.dtype

dtype('float64')

In [ ]:
## datos cargados en tipo int
datos_cargados_int=np.loadtxt("datos.txt", dtype=np.int)
datos_cargados_int.dtype

dtype('int32')

In [ ]:
## redimensionar el array
array_a_guardar=array_a_guardar.reshape((2,5))
array_a_guardar

array([[14,  4, 84, 17, 56],
       [98, 91, 15, 87, 87]])

In [ ]:
## guardar la informacion en un csv
np.savetxt("datos.csv", array_a_guardar, delimiter=",", fmt="%i")

In [ ]:
## guardar varios arrays
matriz_a=np.random.randint(1,100, size=(2,4))
matriz_a

array([[82, 36, 57, 77],
       [91, 25, 11, 55]])

In [ ]:
## guardar matriz
np.savetxt("matriz_a.csv", matriz_a, delimiter=",", fmt="%i")

In [ ]:
## cargar csv
matriz_a_cargada=np.loadtxt("matriz_a.csv", delimiter=",", dtype=float)
matriz_a_cargada

array([[82., 36., 57., 77.],
       [91., 25., 11., 55.]])

In [ ]:
## guardar en archivos binarios
matriz_binaria=np.arange(1,100, 10)
matriz_binaria

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
## guardar en un archivo binario
## sintaxis numpy.save("nombre_archivo.npy")
np.save("archivo_binario.npy",matriz_binaria)

In [ ]:
## cargar archivo binario
## sintaxos: numpy.load(nombre_archivo.npy)
matriz_binaria_cargada=np.load("archivo_binario.npy")
matriz_binaria_cargada

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Modificar arreglos

No se modifíca el arreglo oríginal, se crean otros apartir de esto

In [ ]:
## agregar un elemento en la posición asignada a un arreglo
## sintaxis: np.insert(arreglo, valor, posición)
## creamos un arreglo
array=np.arange(1,10)
np.insert(array, 0, 100)

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [ ]:
## insertar un elemento al final del array
np.append(array, 233)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 233])

In [ ]:
## eliminar un elemento de un array
np.delete(array, -1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
## unir dos arrays
np.concatenate([np.arange(1,10), np.arange(1,10)])

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
## cambiar el tamaño de un array
array=np.arange(1,10)
a=np.resize(array,5)
print(a)


[1 2 3 4 5]


## Ordenamiento

Se ordenan los datos de menor a mayor no es posible ordenar de mayor a menor directamente

In [50]:
## creamos un arreglo
array=np.random.randint(1,10, 10)
array

array([5, 5, 8, 2, 9, 8, 7, 9, 4, 6])

In [51]:
# ordenamos los datos
array.sort()
array

array([2, 4, 5, 5, 6, 7, 8, 8, 9, 9])

In [59]:
# ordenar de manera descendente
array=array[::-1]
array

array([9, 9, 8, 8, 7, 6, 5, 5, 4, 2])

In [61]:
## ordenar los números
array.sort()
array

array([2, 4, 5, 5, 6, 7, 8, 8, 9, 9])

In [67]:
## para ordenar de mayor a menor primero se ordenan los datos
array_desordenado=np.random.randint(1,100, 3)
print(array_desordenado)
## ordenamos el array
array_desordenado.sort()
array_ordenado_ascendente=array_desordenado
print(array_ordenado_ascendente)
## invertimos el array para que este ordenado de forma descendete
array_ordenado_ascendente[::-1]
array_ordenada_descendente=array_ordenado_ascendente[::-1]
print(array_ordenada_descendente)

[52 98 66]
[52 66 98]
[98 66 52]


In [68]:
## lo mismo pero utilizando los metodos directamente desde numpy sin aplicar cambios al array

## para ordenar de mayor a menor primero se ordenan los datos
array_desordenado=np.random.randint(1,100, 3)
print(array_desordenado)
## ordenamos el array
array_ordenado_ascendente=np.sort(array_desordenado)
print(array_ordenado_ascendente)
## invertimos el array para que este ordenado de forma descendete
array_ordenada_descendente=array_ordenado_ascendente[::-1]
print(array_ordenada_descendente)

[64 71  5]
[ 5 64 71]
[71 64  5]
