## Agregación de datos por categoría

In [1]:
## importacion de librerias
import numpy as np
import pandas as pd

In [4]:
## opciones posibles en un dataset
gender = ["male", "female"]
income = ["poor", "middle class", "rich"]

In [5]:
## cantidad de registros en el dummy
n=500

In [10]:
## crear posibilidades aleatorias de genero
gender_data=[np.random.choice(gender) for pos in range(n)]
gender_data

['male',
 'female',
 'male',
 'male',
 'female',
 'male',
 'male',
 'male',
 'female',
 'male',
 'female',
 'male',
 'female',
 'female',
 'female',
 'male',
 'female',
 'female',
 'male',
 'female',
 'female',
 'female',
 'female',
 'male',
 'female',
 'male',
 'male',
 'female',
 'male',
 'female',
 'female',
 'female',
 'male',
 'female',
 'male',
 'female',
 'female',
 'male',
 'male',
 'male',
 'female',
 'male',
 'male',
 'female',
 'female',
 'male',
 'female',
 'female',
 'male',
 'female',
 'male',
 'male',
 'female',
 'male',
 'female',
 'female',
 'female',
 'male',
 'female',
 'female',
 'male',
 'female',
 'female',
 'female',
 'male',
 'male',
 'male',
 'female',
 'female',
 'male',
 'male',
 'male',
 'female',
 'female',
 'female',
 'male',
 'male',
 'male',
 'female',
 'female',
 'female',
 'male',
 'male',
 'male',
 'female',
 'male',
 'male',
 'male',
 'female',
 'female',
 'female',
 'male',
 'male',
 'female',
 'male',
 'female',
 'male',
 'female',
 'male',
 'femal

In [21]:
## nivel economico
income_data=[np.random.choice(income) for pos in range(n)]
income_data

['middle class',
 'middle class',
 'middle class',
 'middle class',
 'rich',
 'middle class',
 'middle class',
 'poor',
 'middle class',
 'rich',
 'poor',
 'rich',
 'rich',
 'middle class',
 'poor',
 'rich',
 'poor',
 'rich',
 'rich',
 'middle class',
 'poor',
 'middle class',
 'rich',
 'rich',
 'middle class',
 'poor',
 'rich',
 'middle class',
 'rich',
 'middle class',
 'rich',
 'rich',
 'rich',
 'rich',
 'rich',
 'rich',
 'middle class',
 'rich',
 'middle class',
 'middle class',
 'middle class',
 'middle class',
 'rich',
 'rich',
 'middle class',
 'middle class',
 'middle class',
 'middle class',
 'middle class',
 'middle class',
 'middle class',
 'poor',
 'poor',
 'middle class',
 'poor',
 'rich',
 'poor',
 'poor',
 'middle class',
 'poor',
 'middle class',
 'rich',
 'poor',
 'rich',
 'rich',
 'poor',
 'poor',
 'poor',
 'poor',
 'poor',
 'middle class',
 'rich',
 'middle class',
 'rich',
 'middle class',
 'rich',
 'rich',
 'poor',
 'rich',
 'rich',
 'middle class',
 'poor',
 'rich

In [12]:
## crear diferentes datas para diferentes caracteristicas
## distribución normal N(m,z): m+n*random m=media, n=desviación tipica z=distribución de números aleatorios, normal 0

In [14]:
height=160+30*np.random.rand(n)
height

array([181.24053718, 176.54784309, 186.89935719, 180.36222936,
       168.78317407, 173.86157069, 178.06642246, 170.13021415,
       172.91539367, 176.54813971, 161.65310216, 172.63761002,
       162.93253085, 162.70464478, 164.42754703, 171.58365961,
       182.02948556, 164.40436675, 180.77510794, 169.06134622,
       185.14879056, 178.64761501, 180.02625187, 181.18174451,
       165.26823183, 177.67954028, 182.79293794, 163.43289378,
       177.38357867, 184.6830822 , 172.56723114, 168.15695517,
       183.54164007, 174.73077623, 176.29322264, 166.11211871,
       169.79937824, 163.36788143, 183.98638089, 187.13272129,
       185.45883335, 187.56004401, 185.46776309, 162.45415272,
       185.49027619, 160.68464086, 174.37818476, 181.98765726,
       165.82761128, 182.79766499, 189.54760004, 165.21825875,
       165.68791213, 180.3104369 , 186.10702051, 161.82061198,
       165.69448663, 161.33406078, 183.33810896, 172.8857892 ,
       179.02606882, 172.28501693, 173.45989729, 162.71

In [29]:
## para pesos
weight=70+40*np.random.rand(n)
weight

array([ 72.06585202,  93.44084478,  72.12003057,  78.09696778,
        75.13086883,  90.76252786,  87.39876095, 109.82760311,
       109.59849212,  87.67920804,  97.72651994,  85.86889175,
        73.3526116 ,  98.98064253,  89.74833378, 107.68167939,
        88.39773025,  75.32976363,  85.05287869, 106.63501137,
       106.40529694,  98.36409686, 104.13619686, 109.49687612,
        97.44867698,  87.63769388,  99.67611056, 107.55095583,
        88.63078419,  77.52109812,  77.89794671,  79.42565819,
        89.40270954, 101.35782603,  80.40363066,  81.77238558,
        94.86209837,  93.44591919,  82.10190755, 100.33371077,
       102.03876896, 103.43675049,  80.88552955,  94.59613113,
        99.49810749, 104.99813389,  84.92266785,  81.27570993,
        82.33466165,  94.58576507,  94.3386142 ,  84.55679179,
        83.2271896 ,  97.65950407,  88.90156573, 109.15161786,
       105.60400754,  87.26042222, 104.53308465,  73.89293924,
        91.19402948,  95.75718384, 109.89794233,  88.62

In [30]:
## para edades
age=60+40+np.random.rand(n)
age

array([100.6933512 , 100.06843991, 100.2600646 , 100.08263498,
       100.14803601, 100.20459485, 100.14045128, 100.5291847 ,
       100.76588363, 100.1546112 , 100.02883076, 100.85493816,
       100.09849057, 100.98323649, 100.73453727, 100.37013537,
       100.55726527, 100.50955679, 100.87241189, 100.3573161 ,
       100.63851686, 100.78077493, 100.9320382 , 100.40370278,
       100.6608152 , 100.30135273, 100.47450485, 100.92015357,
       100.49213605, 100.20679348, 100.16346212, 100.21009264,
       100.61550903, 100.5964499 , 100.97504244, 100.60342995,
       100.41563071, 100.12242082, 100.47491853, 100.88403473,
       100.77739231, 100.64375971, 100.15577829, 100.96712346,
       100.10942657, 100.39059551, 100.39559723, 100.9702502 ,
       100.52705124, 100.18798741, 100.67904   , 100.55454679,
       100.77746092, 100.25651044, 100.17771091, 100.73062632,
       100.1520599 , 100.05492351, 100.5904423 , 100.40893267,
       100.60768774, 100.60988617, 100.52180002, 100.16

In [31]:
## cantidad de ingresos con una media de 8000 pesos y una desviación estandar de 5000 pesos
income=8000+5000*np.random.rand(n)
income

array([12901.49338367, 11155.07916477, 11734.08506197, 11275.31963634,
        8756.3002523 , 12036.08741336, 10538.32511825, 11079.44114927,
       10675.92402708, 10393.73948439, 10937.0153763 , 11963.9238457 ,
       11442.99470619, 12477.51039826, 10680.79724417,  8051.50788989,
       10878.04703605,  9717.09413703,  8917.57250231, 12585.09592811,
       11785.58716591, 12697.98463466,  9454.65681592,  8134.97294001,
        9782.55606697,  8099.51732148, 12496.73690943,  9956.10776307,
       11414.62458415,  9943.99865868,  9640.29439995,  8013.45875589,
       10936.90452566, 11999.91801351,  8647.46145933, 12219.28179061,
       12706.65010144,  9888.61707474, 10304.55535439,  8326.97926973,
        8216.59543743, 10861.51503136, 12048.81170767, 11508.36302099,
        8772.030613  , 12643.02441892,  9387.34255186,  8346.11374866,
       10130.27680789, 12236.19304826, 10878.34944867,  8370.29264302,
        9564.7508077 ,  9926.00948287,  8925.91892825, 10627.8123245 ,
      

In [57]:
dummy=pd.DataFrame({
    "gender": gender_data,
    "economic status": income_data,
    "height": height,
    "weight": weight,
    "income": income 
})
dummy.head()

gender economic status    height     weight        income
0    male    middle class  1.755822  72.065852  12901.493384
1  female    middle class  1.677349  93.440845  11155.079165
2    male    middle class  1.625110  72.120031  11734.085062
3    male    middle class  1.740395  78.096968  11275.319636
4  female            rich  1.810627  75.130869   8756.300252

In [59]:
## agrupación de los datos por categoría
## agrupar los datos por genero
grouped_gender=dummy.groupby("gender")

In [65]:
## ver los grupos de una agrupacion
grouped_gender.groups.keys()

dict_keys(['female', 'male'])

In [66]:
## recorrer los datos de una agrupacion
for group, data in grouped_gender:
    print(group)
    print(data)

female
     gender economic status    height      weight        income
1    female    middle class  1.677349   93.440845  11155.079165
4    female            rich  1.810627   75.130869   8756.300252
8    female    middle class  1.817089  109.598492  10675.924027
10   female            poor  1.673930   97.726520  10937.015376
12   female            rich  1.806869   73.352612  11442.994706
..      ...             ...       ...         ...           ...
494  female    middle class  1.862042   82.062780   8286.776731
495  female            rich  1.829264   88.595397   9763.511387
496  female            rich  1.601570   98.329427   9932.646315
497  female    middle class  1.663324   89.357476  11784.401452
499  female            poor  1.834639   93.302353  10187.785441

[247 rows x 5 columns]
male
    gender economic status    height     weight        income
0     male    middle class  1.755822  72.065852  12901.493384
2     male    middle class  1.625110  72.120031  11734.085062
3     male

In [68]:
## obtener un grupo de un dataframe
grouped_gender.groups["male"]

Int64Index([  0,   2,   3,   5,   6,   7,   9,  11,  15,  18,
            ...
            480, 481, 482, 483, 484, 486, 487, 491, 493, 498],
           dtype='int64', length=253)

In [71]:
## doble agrupación, se hace agrupación por genero y por cada genero se hace una agrupacion para estatus economico
double_group=dummy.groupby(["gender", "economic status"])
len(double_group.groups)

6

In [72]:
# visualizar grupos
double_group.groups

{('female', 'middle class'): [1, 8, 13, 19, 21, 24, 27, 29, 36, 40, 44, 46, 47, 49, 58, 72, 74, 80, 84, 90, 105, 110, 115, 130, 135, 138, 143, 146, 163, 167, 179, 180, 184, 188, 192, 197, 209, 221, 224, 238, 245, 253, 256, 261, 278, 279, 294, 308, 310, 317, 323, 331, 332, 335, 341, 342, 349, 362, 365, 383, 384, 385, 389, 395, 407, 408, 419, 422, 424, 427, 447, 454, 457, 467, 469, 474, 475, 488, 489, 494, 497], ('female', 'poor'): [10, 14, 16, 20, 52, 54, 56, 59, 62, 67, 68, 89, 93, 95, 97, 100, 102, 107, 113, 116, 149, 154, 156, 158, 159, 160, 166, 173, 178, 182, 185, 200, 206, 218, 242, 252, 255, 258, 260, 266, 270, 271, 274, 281, 286, 301, 305, 312, 313, 314, 320, 325, 336, 339, 356, 359, 364, 370, 392, 403, 404, 409, 410, 411, 412, 413, 421, 423, 429, 431, 435, 437, 439, 444, 446, 449, 455, 456, 459, 462, 466, 471, 478, 479, 490, 492, 499], ('female', 'rich'): [4, 12, 17, 22, 30, 31, 33, 35, 43, 55, 61, 63, 73, 78, 79, 88, 99, 101, 108, 109, 117, 120, 122, 134, 136, 137, 141, 144, 1

In [73]:
## visualizamos los nombres de los grupos
double_group.groups.keys()

dict_keys([('female', 'middle class'), ('female', 'poor'), ('female', 'rich'), ('male', 'middle class'), ('male', 'poor'), ('male', 'rich')])

In [81]:
## accceder a una doble agrupación
double_group.groups[('female', "poor")]

Int64Index([ 10,  14,  16,  20,  52,  54,  56,  59,  62,  67,  68,  89,  93,
             95,  97, 100, 102, 107, 113, 116, 149, 154, 156, 158, 159, 160,
            166, 173, 178, 182, 185, 200, 206, 218, 242, 252, 255, 258, 260,
            266, 270, 271, 274, 281, 286, 301, 305, 312, 313, 314, 320, 325,
            336, 339, 356, 359, 364, 370, 392, 403, 404, 409, 410, 411, 412,
            413, 421, 423, 429, 431, 435, 437, 439, 444, 446, 449, 455, 456,
            459, 462, 466, 471, 478, 479, 490, 492, 499],
           dtype='int64')

## Agregación de datos

In [99]:
## suma de datos agrupados
double_group.sum()

height       weight         income
gender economic status                                        
female middle class     142.353593  7461.777789  851476.299331
       poor             152.558757  7744.998490  905722.239837
       rich             137.392249  7237.833452  820241.893563
male   middle class     162.250229  8317.294442  965542.175063
       poor             140.535521  7494.095037  852789.839044
       rich             139.677263  7040.732506  817581.089765

In [100]:
## promedio de datos agrupados
double_group.mean()

height     weight        income
gender economic status                                   
female middle class     1.757452  92.120713  10512.053078
       poor             1.753549  89.022971  10410.600458
       rich             1.739142  91.618145  10382.808779
male   middle class     1.744626  89.433274  10382.173925
       poor             1.735006  92.519692  10528.269618
       rich             1.768067  89.123196  10349.127719

In [101]:
## saber cuantos elementos hay en cada una de las combinaciones
double_group.size()

gender  economic status
female  middle class       81
        poor               87
        rich               79
male    middle class       93
        poor               81
        rich               79
dtype: int64

In [102]:
## informacion de los datos agrupados
double_group.describe()

height                                          \
                        count      mean       std       min       25%   
gender economic status                                                  
female middle class      81.0  1.757452  0.089826  1.600774  1.683545   
       poor              87.0  1.753549  0.090464  1.600276  1.670360   
       rich              79.0  1.739142  0.081930  1.600801  1.672975   
male   middle class      93.0  1.744626  0.079540  1.605277  1.671616   
       poor              81.0  1.735006  0.090463  1.604987  1.651082   
       rich              79.0  1.768067  0.089300  1.602254  1.686245   

                                                     weight             ...  \
                             50%       75%       max  count       mean  ...   
gender economic status                                                  ...   
female middle class     1.740926  1.853815  1.897166   81.0  92.120713  ...   
       poor             1.777059  1.823803  1.899767   87.0  89.022971  ...   
       rich             1.734529  1.806610  1.887143   79.0  91.618145  ...   
male   middle class     1.744999  1.809514  1.894472   93.0  89.433274  ...   
       poor             1.712771  1.809054  1.897227   81.0  92.519692  ...   
       rich             1.784167  1.850606  1.895863   79.0  89.123196  ...   

                                               income                \
                               75%         max  count          mean   
gender economic status                                                
female middle class      99.498107  109.598492   81.0  10512.053078   
       poor              95.412462  109.897942   87.0  10410.600458   
       rich             101.579424  109.705238   79.0  10382.808779   
male   middle class      96.860724  109.568296   93.0  10382.173925   
       poor             102.078889  109.827603   81.0  10528.269618   
       rich              98.652666  109.496876   79.0  10349.127719   

                                                                             \
                                std          min          25%           50%   
gender economic status                                                        
female middle class     1522.719564  8063.880449  9160.395871  10522.107648   
       poor             1317.333313  8041.598548  9548.490063  10382.948429   
       rich             1309.500699  8013.458756  9551.347803  10223.750108   
male   middle class     1474.372453  8095.976701  9063.746431  10258.271413   
       poor             1443.636480  8003.558531  9347.285969  10546.210256   
       rich             1519.595078  8003.574269  8943.507764  10386.232302   

                                                    
                                 75%           max  
gender economic status                              
female middle class     11919.371597  12983.201972  
       poor             11595.594276  12993.322081  
       rich             11361.166623  12887.720155  
male   middle class     11734.085062  12949.622690  
       poor             11657.302703  12982.551337  
       rich             11743.503457  12994.184022  

[6 rows x 24 columns]

In [103]:
## grupo de ingresos
group_income=dummy.groupby("income")

In [110]:
## operaciones por agregacion, cada funcion se hace con cada columna
double_group.aggregate({
    "income": np.sum,
    "height": np.mean
})

income    height
gender economic status                         
female middle class     851476.299331  1.757452
       poor             905722.239837  1.753549
       rich             820241.893563  1.739142
male   middle class     965542.175063  1.744626
       poor             852789.839044  1.735006
       rich             817581.089765  1.768067

In [129]:
## aplicar nuestras propias funciones de agregación con lambda
double_group.aggregate({
    "height": lambda x: (0 if np.sum(x)<100 else 1)
})

height
gender economic status        
female middle class          1
       poor                  1
       rich                  1
male   middle class          1
       poor                  1
       rich                  1

## Filtrado, transformación y otras operaciones

In [139]:
## para filtrar se pasa una funcion lambda que comprueba cada uno de los datos
## devuelve el elemento que dicha comprobación sea verdadera
## filtrar las estaturas de los grupos de acuerdo a la función
## todos los registros con estaturas mayores a 1.5
double_group["height"].filter(lambda h: np.mean(h)>1.5)

0      1.755822
1      1.677349
2      1.625110
3      1.740395
4      1.810627
         ...   
495    1.829264
496    1.601570
497    1.663324
498    1.729974
499    1.834639
Name: height, Length: 500, dtype: float64

In [158]:
dummy["height"].filter(lambda x: np.mean(x)>1)

TypeError: 'function' object is not iterable

In [159]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                          'foo', 'bar'],
                   'B' : [1, 2, 3, 4, 5, 6],
                   'C' : [2.0, 5., 8., 1., 2., 9.]})

In [164]:
grupA=df.groupby('A')
grupA.groups

{'bar': [1, 3, 5], 'foo': [0, 2, 4]}

In [171]:
grupA.filter(lambda x: x['B'].mean() > 3.)

A  B    C
1  bar  2  5.0
3  bar  4  1.0
5  bar  6  9.0

In [172]:
df

A  B    C
0  foo  1  2.0
1  bar  2  5.0
2  foo  3  8.0
3  bar  4  1.0
4  foo  5  2.0
5  bar  6  9.0

In [193]:
np.mean(df.loc[[1, 3, 5], :]["B"].values)

4.0

In [ ]:
dt